comment:
  layout: "header, diff, flags, components"

ignore:
  - "src/application/programs_dev"
  - "tests"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: programs
      name: Programs
      paths:
        - src/application/programs/**
    - component_id: generators
      name: Generators
      paths:
        - src/library_godot/generators/**
    - component_id: parser_clang
      name: ClangParser
      paths:
        - src/library/parsers/libclang/**
    - component_id: parser_treesitter
      name: TreeSitterParser
      paths:
        - src/library/parsers/tree-sitter/**