[Project]
Name=test_files

[Godot]
TargetMajorVersion=4
TargetMinorVersion=6

[Paths]
CachePath=.goc/cache
GeneratedPath=.generated
IgnorePaths=
IncludePaths=/home/luca/Repositories/godot/core,/home/luca/Repositories/godot/scene,/home/luca/Repositories/godot/modules
RootPath=test_files

