name: setup_godot
description: setup_godot
inputs:
  platform:
    required: true
    description: ""
  version:
    required: true
    description: ""
runs:
  using: "composite"
  steps:
    - name: Install Godot (Linux🐧 & MacOS 🍎)
      if: inputs.platform == 'linux.x86_64' || inputs.platform == 'macos.universal'
      shell: sh
      run: |
        INSTALL_DIR=${HOME}/.godot-install-dir/${{inputs.version}}
        mkdir -p $INSTALL_DIR

        echo "Creating $INSTALL_DIR"

        GODOT_DOWNLOAD_URL=https://github.com/godotengine/godot-builds/releases/download/${{inputs.version}}/Godot_v${{inputs.version}}_${{inputs.platform}}.zip

        echo "Downloading: $GODOT_DOWNLOAD_URL"

        cd $INSTALL_DIR
        curl -Lf $GODOT_DOWNLOAD_URL -o godot.zip
        unzip godot.zip
        rm godot.zip

        mv Godot_v${{inputs.version}}_${{inputs.platform}} godot

        ls -la $INSTALL_DIR
        echo $INSTALL_DIR >> $GITHUB_PATH

    - name: Install Godot (Windows 🪟)
      if: inputs.platform == 'win64'
      shell: pwsh
      run: |
        INSTALL_DIR=${HOME}/.godot-install-dir/${{inputs.version}}
        mkdir -p $INSTALL_DIR

        echo "Creating $INSTALL_DIR"

        GODOT_DOWNLOAD_URL=https://github.com/godotengine/godot-builds/releases/download/${{inputs.version}}/Godot_v${{inputs.version}}_${{inputs.platform}}.zip

        echo "Downloading: $GODOT_DOWNLOAD_URL"

        cd $INSTALL_DIR
        curl -Lf $GODOT_DOWNLOAD_URL -o godot.zip
        unzip godot.zip
        rm godot.zip

        mv Godot_v${{inputs.version}}_${{inputs.platform}} godot

        ls -la $INSTALL_DIR
        echo $INSTALL_DIR >> $GITHUB_PATH
