/**************************************************************************/
/* example.generated.h                                                    */
/*                        ___  ___  ___   ___ _____                       */
/*                       / __|/ _ \|   \ / _ \_   _|                      */
/*                      | (_ | (_) | |) | (_) || |                        */
/*                       \___|\___/|___/ \___/ |_|                        */
/*   ___  ___    _ ___ ___ _____    ___ ___  __  __ ___ ___ _    ___ ___  */
/*  / _ \| _ )_ | | __/ __|_   _|  / __/ _ \|  \/  | _ \_ _| |  | __| _ \ */
/* | (_) | _ \ || | _| (__  | |   | (_| (_) | |\/| |  _/| || |__| _||   / */
/*  \___/|___/\__/|___\___| |_|    \___\___/|_|  |_|_| |___|____|___|_|_\ */
/*                                                                        */
/*          This file is generated by Godot Object Compiler 0.1           */
/**************************************************************************/

// NOLINTBEGIN
// clang-format off
#pragma once


#undef GOC_FILE_ID
#define GOC_FILE_ID() 107580388863103421 
 

#include "godot_object_compiler/macros.h"

#include "godot_cpp/classes/wrapped.hpp"
#include "godot_cpp/core/binder_common.hpp"
#include "godot_cpp/core/gdvirtual.gen.inc"
#include "godot_cpp/variant/callable.hpp"
#include "godot_cpp/variant/string_name.hpp"
#define GOC_GENERATED_11_107580388863103421() GDCLASS (ExampleClass, Node) ;\
public:\
static void _bind_methods () ;\
void _notification (int p_notification) ;\
void _get_property_list (godot::List<godot::PropertyInfo> * p_list) const ;\
struct PropertyNames \
{\
  static const godot::StringName& resource() {static const godot::StringName sn = "resource"; return sn; }\
  static const godot::StringName& resources() {static const godot::StringName sn = "resources"; return sn; }\
  static const godot::StringName& range() {static const godot::StringName sn = "range"; return sn; }\
  static const godot::StringName& enum_property() {static const godot::StringName sn = "enum_property"; return sn; }\
  static const godot::StringName& flags_property() {static const godot::StringName sn = "flags_property"; return sn; }\
} ;\
struct FunctionNames \
{\
  static const godot::StringName& function() {static const godot::StringName sn = "function"; return sn; }\
  static const godot::StringName& virtual_function() {static const godot::StringName sn = "virtual_function"; return sn; }\
  static const godot::StringName& rpc_function() {static const godot::StringName sn = "rpc_function"; return sn; }\
} ;\
struct SignalNames \
{\
  static const StringName& something_happened() {static const StringName sn = "something_happened"; return sn; }\
} ;\
godot::Callable function_callable{this, "function"};\
godot::Callable virtual_function_callable{this, "virtual_function"};\
godot::Callable rpc_function_callable{this, "rpc_function"};\
godot::Ref <godot::Resource> get_resource () const ;\
void set_resource (const godot::Ref <godot::Resource> & p_resource) ;\
godot::TypedDictionary <int, godot::Resource> get_resources () const ;\
float get_range () const ;\
void set_range (const float & p_range) ;\
int get_enum_property () const ;\
void set_enum_property (int p_enum_property) ;\
int get_flags_property () const ;\
void set_flags_property (int p_flags_property) ;\
protected:\
private:\
void _virtual_function (Node * p_node) ;\
GDVIRTUAL1 (_virtual_function, godot::Node *) ;\
void set_resources (const godot::TypedDictionary <int, godot::Resource> & p_resources) ; 
 

#define GOC_GENERATED_59_107580388863103421() VARIANT_ENUM_CAST (ExampleClass::Regular) ;\
VARIANT_BITFIELD_CAST (ExampleClass::Flags) ; 
 

// clang-format on
// NOLINTEND
