/**************************************************************************/
/*                                                                        */
/*                        ___  ___  ___   ___ _____                       */
/*                       / __|/ _ \|   \ / _ \_   _|                      */
/*                      | (_ | (_) | |) | (_) || |                        */
/*                       \___|\___/|___/ \___/ |_|                        */
/*   ___  ___    _ ___ ___ _____    ___ ___  __  __ ___ ___ _    ___ ___  */
/*  / _ \| _ )_ | | __/ __|_   _|  / __/ _ \|  \/  | _ \_ _| |  | __| _ \ */
/* | (_) | _ \ || | _| (__  | |   | (_| (_) | |\/| |  _/| || |__| _||   / */
/*  \___/|___/\__/|___\___| |_|    \___\___/|_|  |_|_| |___|____|___|_|_\ */
/*                                                                        */
/*          This file is generated by Godot Object Compiler 0.1           */
/**************************************************************************/

// NOLINTBEGIN
// clang-format off
#include "example.h"

#include "example.h"
#include "godot_cpp/classes/global_constants.hpp"
#include "godot_cpp/classes/multiplayer_api.hpp"
#include "godot_cpp/classes/multiplayer_peer.hpp"
#include "godot_cpp/classes/node.hpp"
#include "godot_cpp/classes/ref.hpp"
#include "godot_cpp/classes/resource.hpp"
#include "godot_cpp/classes/wrapped.hpp"
#include "godot_cpp/core/class_db.hpp"
#include "godot_cpp/core/object.hpp"
#include "godot_cpp/core/property_info.hpp"
#include "godot_cpp/variant/dictionary.hpp"
#include "godot_cpp/variant/typed_dictionary.hpp"
#include "godot_cpp/variant/variant.hpp"

void ExampleClass::_bind_methods () 
{
  BIND_ENUM_CONSTANT (REGULAR_VALUE_A) ;
  BIND_ENUM_CONSTANT (REGULAR_VALUE_B) ;
  BIND_ENUM_CONSTANT (REGULAR_VALUE_C) ;
  BIND_BITFIELD_FLAG (FLAG_NONE) ;
  BIND_BITFIELD_FLAG (FLAG_VALUE_A) ;
  BIND_BITFIELD_FLAG (FLAG_VALUE_B) ;
  BIND_BITFIELD_FLAG (FLAG_VALUE_C) ;
  ADD_SIGNAL (MethodInfo ("something_happened", godot::PropertyInfo (godot::Variant::INT, "p_param", godot::PropertyHint::PROPERTY_HINT_NONE, "", godot::PropertyUsageFlags::PROPERTY_USAGE_DEFAULT))) ;
  godot::ClassDB::bind_method (D_METHOD ("function", "p_node"), &ExampleClass::function) ;
  GDVIRTUAL_BIND (_virtual_function, "p_node") ;
  godot::ClassDB::bind_method (D_METHOD ("virtual_function", "p_node"), &ExampleClass::_virtual_function) ;
  godot::ClassDB::bind_method (D_METHOD ("rpc_function", "p_param"), &ExampleClass::rpc_function) ;
  ADD_GROUP ("Properties", "") ;
  godot::ClassDB::bind_method (D_METHOD ("get_resource"), &ExampleClass::get_resource) ;
  godot::ClassDB::bind_method (D_METHOD ("set_resource", "resource"), &ExampleClass::set_resource) ;
  ADD_PROPERTY (godot::PropertyInfo (godot::Variant::OBJECT, "resource", godot::PropertyHint::PROPERTY_HINT_RESOURCE_TYPE, "Resource", godot::PropertyUsageFlags::PROPERTY_USAGE_DEFAULT), "set_resource", "get_resource") ;
  godot::ClassDB::bind_method (D_METHOD ("get_resources"), &ExampleClass::get_resources) ;
  godot::ClassDB::bind_method (D_METHOD ("set_resources", "resources"), &ExampleClass::set_resources) ;
  ADD_PROPERTY (godot::PropertyInfo (godot::Variant::DICTIONARY, "resources", godot::PropertyHint::PROPERTY_HINT_DICTIONARY_TYPE, vformat("%s/%s:%s;%s/%s:%s", Variant::INT,PROPERTY_HINT_NONE,"",Variant::OBJECT,PROPERTY_HINT_RESOURCE_TYPE,"Resource"), godot::PropertyUsageFlags::PROPERTY_USAGE_DEFAULT), "set_resources", "get_resources") ;
  godot::ClassDB::bind_method (D_METHOD ("get_range"), &ExampleClass::get_range) ;
  godot::ClassDB::bind_method (D_METHOD ("set_range", "range"), &ExampleClass::set_range) ;
  ADD_PROPERTY (godot::PropertyInfo (godot::Variant::FLOAT, "range", godot::PropertyHint::PROPERTY_HINT_RANGE, "0,1,0.1", godot::PropertyUsageFlags::PROPERTY_USAGE_DEFAULT), "set_range", "get_range") ;
  ADD_GROUP ("Enum Properties", "") ;
  godot::ClassDB::bind_method (D_METHOD ("get_enum_property"), &ExampleClass::get_enum_property) ;
  godot::ClassDB::bind_method (D_METHOD ("set_enum_property", "enum_property"), &ExampleClass::set_enum_property) ;
  ADD_PROPERTY (godot::PropertyInfo (godot::Variant::INT, "enum_property", godot::PropertyHint::PROPERTY_HINT_ENUM, "Regular Value A:0,Regular Value B:1,Regular Value C:2", godot::PropertyUsageFlags::PROPERTY_USAGE_DEFAULT), "set_enum_property", "get_enum_property") ;
  godot::ClassDB::bind_method (D_METHOD ("get_flags_property"), &ExampleClass::get_flags_property) ;
  godot::ClassDB::bind_method (D_METHOD ("set_flags_property", "flags_property"), &ExampleClass::set_flags_property) ;
  ADD_PROPERTY (godot::PropertyInfo (godot::Variant::INT, "flags_property", godot::PropertyHint::PROPERTY_HINT_ENUM, "Flag None:0,Flag Value A:1,Flag Value B:2,Flag Value C:4", godot::PropertyUsageFlags::PROPERTY_USAGE_DEFAULT), "set_flags_property", "get_flags_property") ;
}
void ExampleClass::_notification (int p_notification) 
{
  if (p_notification == NOTIFICATION_ENTER_TREE) 
  {
    
    {
        godot::Dictionary opts;
        opts["rpc_mode"] = godot::MultiplayerAPI::RPC_MODE_AUTHORITY;
        opts["transfer_mode"] = godot::MultiplayerPeer::TRANSFER_MODE_UNRELIABLE_ORDERED;
        opts["call_local"] = true;
        opts["channel"] = 1;
        rpc_config("rpc_function", opts);
    }
  }
}
void ExampleClass::something_happened (int p_param) 
{
  emit_signal ("something_happened", p_param) ;
}
void ExampleClass::_virtual_function (godot::Node * p_node) 
{
  if(! GDVIRTUAL_CALL (_virtual_function, p_node))
  {
    return virtual_function (p_node) ;
  }
}
godot::Ref <godot::Resource> ExampleClass::get_resource () const 
{
  return resource;
}
void ExampleClass::set_resource (const godot::Ref <godot::Resource> & p_resource) 
{
  resource = p_resource;
}
godot::TypedDictionary <int, godot::Resource> ExampleClass::get_resources () const 
{
  return resources;
}
void ExampleClass::set_resources (const godot::TypedDictionary <int, godot::Resource> & p_resources) 
{
  resources = p_resources;
}
float ExampleClass::get_range () const 
{
  return range;
}
void ExampleClass::set_range (const float & p_range) 
{
  range = p_range;
}
int ExampleClass::get_enum_property () const 
{
  return enum_property;
}
void ExampleClass::set_enum_property (int p_enum_property) 
{
  enum_property = static_cast<ExampleClass::Regular>(p_enum_property);
}
int ExampleClass::get_flags_property () const 
{
  return flags_property;
}
void ExampleClass::set_flags_property (int p_flags_property) 
{
  flags_property = static_cast<ExampleClass::Flags>(p_flags_property);
}
// clang-format on
// NOLINTEND
