/**************************************************************************/
/* example.generated.cpp                                                  */
/*                        ___  ___  ___   ___ _____                       */
/*                       / __|/ _ \|   \ / _ \_   _|                      */
/*                      | (_ | (_) | |) | (_) || |                        */
/*                       \___|\___/|___/ \___/ |_|                        */
/*   ___  ___    _ ___ ___ _____    ___ ___  __  __ ___ ___ _    ___ ___  */
/*  / _ \| _ )_ | | __/ __|_   _|  / __/ _ \|  \/  | _ \_ _| |  | __| _ \ */
/* | (_) | _ \ || | _| (__  | |   | (_| (_) | |\/| |  _/| || |__| _||   / */
/*  \___/|___/\__/|___\___| |_|    \___\___/|_|  |_|_| |___|____|___|_|_\ */
/*                                                                        */
/*          This file is generated by Godot Object Compiler 0.1           */
/**************************************************************************/

// NOLINTBEGIN
// clang-format off
#include "purged local file path"
#include <godot_cpp/classes/multiplayer_api.hpp>
#include <godot_cpp/classes/multiplayer_peer.hpp>
void ExampleClass::_bind_methods () 
{
  BIND_ENUM_CONSTANT (REGULAR_VALUE_A) ;
  BIND_ENUM_CONSTANT (REGULAR_VALUE_B) ;
  BIND_ENUM_CONSTANT (REGULAR_VALUE_C) ;
  BIND_BITFIELD_FLAG (FLAG_NONE) ;
  BIND_BITFIELD_FLAG (FLAG_VALUE_A) ;
  BIND_BITFIELD_FLAG (FLAG_VALUE_B) ;
  BIND_BITFIELD_FLAG (FLAG_VALUE_C) ;
  ADD_SIGNAL (MethodInfo ("something_happened", PropertyInfo (Variant::INT, "p_p_param", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT))) ;
  ClassDB::bind_method (D_METHOD ("function", "p_node"), &ExampleClass::function) ;
  GDVIRTUAL_BIND (_virtual_function, "p_node") ;
  ClassDB::bind_method (D_METHOD ("virtual_function", "p_node"), &ExampleClass::_virtual_function) ;
  ClassDB::bind_method (D_METHOD ("rpc_function", "p_param"), &ExampleClass::rpc_function) ;
  ClassDB::bind_method (D_METHOD ("get_resource"), &ExampleClass::get_resource) ;
  ClassDB::bind_method (D_METHOD ("set_resource", "resource"), &ExampleClass::set_resource) ;
  ADD_PROPERTY (PropertyInfo (Variant::OBJECT, "resource", PROPERTY_HINT_RESOURCE_TYPE, "Resource", (PROPERTY_USAGE_DEFAULT) & ~PROPERTY_USAGE_EDITOR), "set_resource", "get_resource") ;
  ClassDB::bind_method (D_METHOD ("get_resources"), &ExampleClass::get_resources) ;
  ClassDB::bind_method (D_METHOD ("set_resources", "resources"), &ExampleClass::set_resources) ;
  ADD_PROPERTY (PropertyInfo (Variant::DICTIONARY, "resources", PROPERTY_HINT_DICTIONARY_TYPE, vformat("%s/%s:%s;%s/%s:%s", Variant::INT,PROPERTY_HINT_NONE,"",Variant::OBJECT,PROPERTY_HINT_RESOURCE_TYPE,"Resource"), (PROPERTY_USAGE_DEFAULT) & ~PROPERTY_USAGE_EDITOR), "set_resources", "get_resources") ;
  ClassDB::bind_method (D_METHOD ("get_range"), &ExampleClass::get_range) ;
  ClassDB::bind_method (D_METHOD ("set_range", "range"), &ExampleClass::set_range) ;
  ADD_PROPERTY (PropertyInfo (Variant::FLOAT, "range", PROPERTY_HINT_RANGE, "0,1,0.1", (PROPERTY_USAGE_DEFAULT) & ~PROPERTY_USAGE_EDITOR), "set_range", "get_range") ;
  ClassDB::bind_method (D_METHOD ("get_enum_property"), &ExampleClass::get_enum_property) ;
  ClassDB::bind_method (D_METHOD ("set_enum_property", "enum_property"), &ExampleClass::set_enum_property) ;
  ADD_PROPERTY (PropertyInfo (Variant::INT, "enum_property", PROPERTY_HINT_ENUM, "Regular Value A:0,Regular Value B:1,Regular Value C:2", (PROPERTY_USAGE_DEFAULT) & ~PROPERTY_USAGE_EDITOR), "set_enum_property", "get_enum_property") ;
  ClassDB::bind_method (D_METHOD ("get_flags_property"), &ExampleClass::get_flags_property) ;
  ClassDB::bind_method (D_METHOD ("set_flags_property", "flags_property"), &ExampleClass::set_flags_property) ;
  ADD_PROPERTY (PropertyInfo (Variant::INT, "flags_property", PROPERTY_HINT_FLAGS, "Flag None:0,Flag Value A:1,Flag Value B:2,Flag Value C:4", (PROPERTY_USAGE_DEFAULT) & ~PROPERTY_USAGE_EDITOR), "set_flags_property", "get_flags_property") ;
}
void ExampleClass::_notification (int p_notification) 
{
  if (p_notification == NOTIFICATION_ENTER_TREE) 
  {
    
    {
        Dictionary opts;
        opts["rpc_mode"] = MultiplayerAPI::RPC_MODE_AUTHORITY;
        opts["transfer_mode"] = MultiplayerPeer::TRANSFER_MODE_UNRELIABLE_ORDERED;
        opts["call_local"] = true;
        opts["channel"] = 1;
        rpc_config("rpc_function", opts);
    }
  }
}
void ExampleClass::_get_property_list (List<PropertyInfo> * p_list) const 
{
  p_list->push_back (PropertyInfo (Variant::NIL, "Properties", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_CATEGORY)) ;
  p_list->push_back (PropertyInfo (Variant::OBJECT, "resource", PROPERTY_HINT_RESOURCE_TYPE, "Resource", PROPERTY_USAGE_DEFAULT)) ;
  p_list->push_back (PropertyInfo (Variant::DICTIONARY, "resources", PROPERTY_HINT_DICTIONARY_TYPE, vformat("%s/%s:%s;%s/%s:%s", Variant::INT,PROPERTY_HINT_NONE,"",Variant::OBJECT,PROPERTY_HINT_RESOURCE_TYPE,"Resource"), PROPERTY_USAGE_DEFAULT)) ;
  p_list->push_back (PropertyInfo (Variant::FLOAT, "range", PROPERTY_HINT_RANGE, "0,1,0.1", PROPERTY_USAGE_DEFAULT)) ;
  p_list->push_back (PropertyInfo (Variant::NIL, "Enum Properties", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_GROUP)) ;
  p_list->push_back (PropertyInfo (Variant::INT, "enum_property", PROPERTY_HINT_ENUM, "Regular Value A:0,Regular Value B:1,Regular Value C:2", PROPERTY_USAGE_DEFAULT)) ;
  p_list->push_back (PropertyInfo (Variant::INT, "flags_property", PROPERTY_HINT_FLAGS, "Flag None:0,Flag Value A:1,Flag Value B:2,Flag Value C:4", PROPERTY_USAGE_DEFAULT)) ;
}
void ExampleClass::something_happened (int p_p_param) 
{
  emit_signal ("something_happened", p_p_param) ;
}
void ExampleClass::_virtual_function (Node * p_node) 
{
  if(! GDVIRTUAL_CALL (_virtual_function, p_node))
  {
    return virtual_function (p_node) ;
  }
}
Ref <Resource> ExampleClass::get_resource () const 
{
  return resource;
}
void ExampleClass::set_resource (const Ref <Resource> & p_resource) 
{
  resource = p_resource;
}
TypedDictionary <int, Resource> ExampleClass::get_resources () const 
{
  return resources;
}
void ExampleClass::set_resources (const TypedDictionary <int, Resource> & p_resources) 
{
  resources = p_resources;
}
float ExampleClass::get_range () const 
{
  return range;
}
void ExampleClass::set_range (const float & p_range) 
{
  range = p_range;
}
int ExampleClass::get_enum_property () const 
{
  return enum_property;
}
void ExampleClass::set_enum_property (int p_enum_property) 
{
  enum_property = static_cast<ExampleClass::Regular>(p_enum_property);
}
int ExampleClass::get_flags_property () const 
{
  return flags_property;
}
void ExampleClass::set_flags_property (int p_flags_property) 
{
  flags_property = static_cast<ExampleClass::Flags>(p_flags_property);
}
// clang-format on
// NOLINTEND

