/**************************************************************************/
/* generated_register_types.h                                             */
/*                        ___  ___  ___   ___ _____                       */
/*                       / __|/ _ \|   \ / _ \_   _|                      */
/*                      | (_ | (_) | |) | (_) || |                        */
/*                       \___|\___/|___/ \___/ |_|                        */
/*   ___  ___    _ ___ ___ _____    ___ ___  __  __ ___ ___ _    ___ ___  */
/*  / _ \| _ )_ | | __/ __|_   _|  / __/ _ \|  \/  | _ \_ _| |  | __| _ \ */
/* | (_) | _ \ || | _| (__  | |   | (_| (_) | |\/| |  _/| || |__| _||   / */
/*  \___/|___/\__/|___\___| |_|    \___\___/|_|  |_|_| |___|____|___|_|_\ */
/*                                                                        */
/*          This file is generated by Godot Object Compiler 0.1           */
/**************************************************************************/

// NOLINTBEGIN
// clang-format off
#pragma once


#include "godot_cpp/godot.hpp"
using namespace godot;

void generated_register_module (godot::ModuleInitializationLevel p_level) ;
void generated_unregister_module (godot::ModuleInitializationLevel p_level) ;
// clang-format on
// NOLINTEND
