name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install cmake -y
          sudo apt install mold -y

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake .. -DGOC_TESTS_ENABLED=ON
          make -j$(nproc)
          cd ..

      - name: Checkout godot-cpp
        uses: actions/checkout@v4
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Install Scons
        run: |
          sudo apt install scons -y

      - name: Generate godot-cpp
        run: |
          cd godot-cpp
          scons
          cd ..

      - name: Run Tests
        run: |
          ./build/goc_tests run_integration_tests godot-cpp/include godot-cpp/gen/include
