name: Mac Build
on:
  workflow_call:
    inputs:
      create_artifact:
        required: false
        type: boolean
        default: false

jobs:
  mac-build:
    name: Build (Mac 🍎)
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v7
        with:
          submodules: "true"

      - name: Install Packages
        run: |
          brew install tree-sitter-cli
          brew install scons

      - name: Setup libclang
        uses: ./.github/actions/setup_libclang
        with:
          platform: "macos"

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DGOC_TESTS_ENABLED=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"  -DClang_DIR=libclang/lib/cmake/clang/
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN)

      - name: Checkout godot-cpp
        uses: actions/checkout@v7
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"

      - name: Generate godot-cpp bindings
        run: |
          cd godot-cpp
          mkdir build
          cd build
          cmake ..
          cmake --build . --target generate_bindings

      - name: Run Tests
        run: |
          ./build/goc_tests run_integration_tests godot-cpp/gdextension/extension_api.json godot-cpp/include godot-cpp/build/gen/include godot-cpp/gdextension

      - name: Upload Binary
        if: ${{inputs.create_artifact == true}}
        uses: actions/upload-artifact@v7
        with:
          name: macos-binary
          path: build/goc
          compression-level: 9
          if-no-files-found: error
          overwrite: true
