name: Generate godot-cpp
on:
  workflow_call:
    secrets:
      GOC_RUNNER_TOKEN:
        required: true

jobs:
  generate-godot-cpp:
    name: Generate godot-cpp
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout godot-cpp
        uses: actions/checkout@v4
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{github.workspace}}/godot-cpp/.scons_cache/
          key: godot-cpp-cache

      - name: Install Scons
        run: |
          sudo apt-get update
          sudo apt-get install scons -y

      - name: Generate godot-cpp
        run: |
          cd godot-cpp
          scons
          cd ..

      - name: Save Include Cache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/godot-cpp/include
            ${{github.workspace}}/godot-cpp/gen/include
          key: godot-cpp-include-cache

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/godot-cpp/.scons_cache/
          key: godot-cpp-cache
