name: Linux Build
on:
  workflow_call:
    inputs:
      create_artifact:
        required: false
        type: boolean
        default: false
    secrets:
      GOC_RUNNER_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  linux-build:
    name: Build (Linux 🐧)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install cmake -y
          sudo apt install scons -y

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DGOC_TESTS_ENABLED=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN)

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Restore godot-cpp Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/godot-cpp/.scons_cache/
          key: linux-godot-cpp

      - name: Build godot-cpp
        env:
          SCONS_CACHE: ${{github.workspace}}/godot-cpp/.scons_cache/
        run: |
          cd godot-cpp
          scons
          cd ..

      - name: Save godot-cpp Cache
        uses: actions/cache/save@v5
        with:
          path: ${{github.workspace}}/godot-cpp/.scons_cache/
          key: linux-godot-cpp

      - name: Run Tests
        run: |
          ./build/goc_tests run_integration_tests godot-cpp/gdextension/extension_api.json godot-cpp/include godot-cpp/gen/include
          pip install gcovr
          cd ./build/CMakeFiles/goc_tests.dir/src
          gcovr -f . -e "/usr/include/.*" -e "/.*thirdparty/.*" -e "/.*tests/.*"\
            --merge-mode-functions=merge-use-line-min\
            --exclude-unreachable-branches\
            --exclude-throw-branches\
            --exclude-noncode-lines\
            --exclude-lines-by-pattern .*PANIC_COND\
            --sonarqube coverage.xml\
            --cobertura coverage.cobertura.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./build/CMakeFiles/goc_tests.dir/src/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=./build/compile_commands.json
            --define sonar.coverageReportPaths=./build/CMakeFiles/goc_tests.dir/src/coverage.xml

  linux-test-project:
    name: Run Test Project (Linux 🐧)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Test Repo
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler-test"
          submodules: "false"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Checkout Godot Object Compiler
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler"
          submodules: "recursive"
          path: "godot-object-compiler"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          submodules: "true"
          path: "godot-cpp"
          ref: "4.5"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install cmake -y

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN)

      - name: Install Godot
        shell: bash
        run: |
          INSTALL_DIR=${HOME}/.godot-install-dir/4.5.1-stable
          mkdir -p $INSTALL_DIR

          echo "Creating $INSTALL_DIR"

          GODOT_DOWNLOAD_URL=https://github.com/godotengine/godot-builds/releases/download/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip

          echo "Downloading: $GODOT_DOWNLOAD_URL"

          cd $INSTALL_DIR
          wget -O godot.zip -q $GODOT_DOWNLOAD_URL
          unzip godot.zip
          rm -rf godot.zip

          mv Godot_v4.5.1-stable_linux.x86_64 godot

          ls -la $INSTALL_DIR
          echo $INSTALL_DIR >> $GITHUB_PATH

      - name: Run Project
        run: |
          godot --headless --path project --editor --quit || true # Godot 4.5.1 crashes after successful import, ignore for now
          godot --headless --path project

      - name: Upload Binary
        if: ${{inputs.create_artifact == true}}
        uses: actions/upload-artifact@v7
        with:
          name: linux-binary
          path: build/godot-object-compiler/goc
          compression-level: 9
          if-no-files-found: error
          overwrite: true
