name: Windows Build
on:
  workflow_call:
    inputs:
      create_artifact:
        required: false
        type: boolean
        default: false
    secrets:
      GOC_RUNNER_TOKEN:
        required: true
jobs:
  windows-build:
    name: Build (Windows 🪟)
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Checkout godot-cpp
        uses: actions/checkout@v4
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Setup TreeSitter
        run: |
          choco install tree-sitter

      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{github.workspace}}/build/
            ${{github.workspace}}/godot-cpp/.scons_cache/
          key: build-cache-windows

      - name: Build Project
        run: |
          mkdir build -Force
          cmake -Bbuild -S. -DGOC_TESTS_ENABLED=ON
          cmake --build build --config Release
      #
      - name: Install Scons
        run: |
          python.exe -m pip install scons

      - name: Generate godot-cpp
        run: |
          cd godot-cpp
          scons
          cd ..

      - name: Run Tests
        run: |
          ./build/goc_tests.exe run_integration_tests godot-cpp/include godot-cpp/gen/include

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/build/
            ${{github.workspace}}/godot-cpp/.scons_cache/
          key: build-cache-windows

      - name: Upload Binary
        if: ${{inputs.create_artifact == true}}
        uses: actions/upload-artifact@v7
        with:
          name: windows-binary
          path: build/goc.exe
          compression-level: 9
          if-no-files-found: error
          overwrite: true
