name: Linux Build
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  linux-build:
    name: Build (Linux 🐧)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install cmake scons -y

      - name: Setup libclang
        uses: ./.github/actions/setup_libclang
        with:
          platform: "linux"

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DGOC_TESTS_ENABLED=ON -DCMAKE_BUILD_TYPE=Release -DClang_DIR=libclang/lib/cmake/clang/
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN)

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"

      - name: Restore godot-cpp Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/godot-cpp/.scons_cache/
          key: linux-godot-cpp

      - name: Build godot-cpp
        env:
          SCONS_CACHE: ${{github.workspace}}/godot-cpp/.scons_cache/
        run: |
          cd godot-cpp
          scons
          cd ..

      - name: Save godot-cpp Cache
        uses: actions/cache/save@v5
        with:
          path: ${{github.workspace}}/godot-cpp/.scons_cache/
          key: linux-godot-cpp

      - name: Run Tests
        run: |
          ./build/goc_tests run_integration_tests godot-cpp/gdextension/extension_api.json godot-cpp/include godot-cpp/gen/include godot-cpp/gdextension
          pip install gcovr
          cd ./build/CMakeFiles/goc_tests.dir/src
          gcovr -f . -e "/usr/include/.*" -e "/.*thirdparty/.*" -e "/.*tests/.*"\
            --merge-mode-functions=merge-use-line-min\
            --exclude-unreachable-branches\
            --exclude-throw-branches\
            --exclude-noncode-lines\
            --exclude-lines-by-pattern .*PANIC_COND\
            --exclude-lines-by-pattern .*ERROR_COND\
            --exclude-lines-by-pattern .*RESULT_ERROR_PASS_ON\
            --sonarqube coverage.xml\
            --cobertura coverage.cobertura.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./build/CMakeFiles/goc_tests.dir/src/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
