name: Windows Build
on:
  workflow_call:
    inputs:
      create_artifact:
        required: false
        type: boolean
        default: false
    secrets:
      GOC_RUNNER_TOKEN:
        required: true
jobs:
  windows-build:
    name: Build (Windows 🪟)
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install Packages
        run: |
          choco install tree-sitter
          python -m pip install scons

      - name: Build Project
        run: |
          mkdir build -Force
          cmake -Bbuild -S. -DGOC_TESTS_ENABLED=ON
          cmake --build build --config Release

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          ref: "4.5"
          path: "godot-cpp"
          token: ${{secrets.GOC_RUNNER_TOKEN}}

      - name: Restore godot-cpp Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/godot-cpp/.scons_cache/
          key: windows-godot-cpp

      - name: Build godot-cpp
        env:
          SCONS_CACHE: ${{github.workspace}}/godot-cpp/.scons_cache/
        run: |
          cd godot-cpp
          scons
          cd ..

      - name: Save godot-cpp Cache
        uses: actions/cache/save@v5
        with:
          path: ${{github.workspace}}/godot-cpp/.scons_cache/
          key: windows-godot-cpp

      - name: Run Tests
        run: |
          ./build/goc_tests.exe run_integration_tests godot-cpp/gdextension/extension_api.json godot-cpp/include godot-cpp/gen/include

      - name: Upload Binary
        if: ${{inputs.create_artifact == true}}
        uses: actions/upload-artifact@v7
        with:
          name: windows-binary
          path: build/goc.exe
          compression-level: 9
          if-no-files-found: error
          overwrite: true
