name: Nightly Workflow
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  check-changed:
    runs-on: ubuntu-22.04
    outputs:
      result: ${{ steps.compare.outputs.result }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
      - id: compare
        name: Compare Commit Hashes
        run: |
          gh release download nightly -p goc_nightly-linux.x86_64.zip
          unzip goc_nightly-linux.x86_64.zip
          chmod +x ./linux/goc
          ./linux/goc build_num >> last_hash
          git rev-parse HEAD >> current_hash
          diff last_hash current_hash && echo "result=0" >> ${GITHUB_OUTPUT} || echo "result=1" >> ${GITHUB_OUTPUT}

  check-format:
    needs: check-changed
    if: ${{ needs.check-changed.outputs.result == 1 }}
    uses: ./.github/workflows/format.yml

  linux-build:
    uses: ./.github/workflows/build_linux.yml
    needs: [check-format, check-changed]
    if: ${{ needs.check-changed.outputs.result == 1 }}
    with:
      create_artifact: true
    secrets:
      GOC_RUNNER_TOKEN: ${{secrets.GOC_RUNNER_TOKEN}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

  windows-build:
    uses: ./.github/workflows/build_windows.yml
    needs: [check-format, check-changed]
    if: ${{ needs.check-changed.outputs.result == 1 }}
    with:
      create_artifact: true
    secrets:
      GOC_RUNNER_TOKEN: ${{secrets.GOC_RUNNER_TOKEN}}

  mac-build:
    uses: ./.github/workflows/build_mac.yml
    needs: [check-format, check-changed]
    if: ${{ needs.check-changed.outputs.result == 1 }}
    with:
      create_artifact: true
    secrets:
      GOC_RUNNER_TOKEN: ${{secrets.GOC_RUNNER_TOKEN}}

  upload-artifacts:
    name: Upload release artifacts
    runs-on: ubuntu-22.04
    needs: [linux-build, windows-build, mac-build, check-changed]
    if: ${{ needs.check-changed.outputs.result == 1 }}
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          submodules: "false"

      - name: Download Linux Artifact
        uses: actions/download-artifact@v8
        with:
          name: linux-binary
          path: linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v8
        with:
          name: windows-binary
          path: windows

      - name: Download Mac Artifact
        uses: actions/download-artifact@v8
        with:
          name: macos-binary
          path: macos

      - name: Add Artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip goc_nightly-linux.x86_64.zip linux/goc
          zip goc_nightly-win64.zip windows/goc.exe
          zip goc_nightly-macos.universal.zip macos/goc

          gh release upload nightly goc_nightly-linux.x86_64.zip --clobber
          gh release upload nightly goc_nightly-win64.zip --clobber
          gh release upload nightly goc_nightly-macos.universal.zip --clobber

      - uses: Ayowel/butler-to-itch@v1
        with:
          butler_key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: lucatuerk
          itch_game: godot-object-compiler
          version: nightly
          files: |
            windows windows/goc.exe
            linux linux/goc
            mac macos/goc
