name: Nightly Workflow
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - nightly_workflow

jobs:
  check-format:
    uses: ./.github/workflows/format.yml

  linux-build:
    uses: ./.github/workflows/build_linux.yml
    needs: check-format
    with:
      create_artifact: true
    secrets:
      GOC_RUNNER_TOKEN: ${{secrets.GOC_RUNNER_TOKEN}}

  # windows-build:
  #   uses: ./.github/workflows/build_windows.yml
  #   needs: linux-build
  #   with:
  #     create_artifact: true
  #   secrets:
  #     GOC_RUNNER_TOKEN: ${{secrets.GOC_RUNNER_TOKEN}}

  download-linux-artifacts:
    runs-on: ubuntu-22.04
    needs: linux-build
    permissions: write-all

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: "false"

      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          name: linux-binary

      - name: Add Artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip goc-x64-linux.zip goc
          gh release upload nightly goc-x64-linux.zip
