name: Nightly Workflow
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-format:
    uses: ./.github/workflows/format.yml

  linux-build:
    uses: ./.github/workflows/build_linux.yml
    needs: check-format
    with:
      create_artifact: true

  windows-build:
    uses: ./.github/workflows/build_windows.yml
    needs: linux-build
    with:
      create_artifact: true

  download-linux-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-binary

      - name: Add Artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip goc-x64-linux.zip goc
          gh release upload nightly goc-x64-linux.zip