name: Linux Run Test Project
on:
  workflow_call:

jobs:
  linux-test-project:
    name: Run Test Project (Linux 🐧)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Test Repo
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler-test"
          submodules: "false"

      - name: Checkout Godot Object Compiler
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler"
          submodules: "recursive"
          path: "godot-object-compiler"

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          submodules: "true"
          path: "godot-cpp"
          ref: "4.5"

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install cmake -y

      - name: Setup libclang
        uses: ./godot-object-compiler/.github/actions/setup_libclang
        with:
          platform: "linux"

      - name: Install Godot
        uses: ./godot-object-compiler/.github/actions/setup_godot
        with:
          platform: "linux.x86_64"
          version: "4.6.3-stable"

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release -DClang_DIR=${{github.workspace}}/libclang/lib/cmake/clang/
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN)

      - name: Run Project
        run: |
          ./godot --headless --path project --editor --quit || true
          ./godot --headless --path project

  windows-test-project:
    name: Run Test Project (Windows 🪟)
    runs-on: windows-latest
    steps:
      - name: Checkout Test Repo
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler-test"
          submodules: "false"

      - name: Checkout Godot Object Compiler
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler"
          submodules: "recursive"
          path: "godot-object-compiler"

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          submodules: "true"
          path: "godot-cpp"
          ref: "4.5"

      - name: Install Packages
        run: |
          choco install tree-sitter
          python -m pip install scons

      - name: Setup libclang
        uses: ./godot-object-compiler/.github/actions/setup_libclang
        with:
          platform: "windows"

      - name: Install Godot
        uses: ./godot-object-compiler/.github/actions/setup_godot
        with:
          platform: "win64"
          version: "4.6.3-stable"

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DClang_DIR=${{github.workspace}}/libclang/lib/cmake/clang/
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN) --config Release

      - name: Run Project
        run: |
          .\godot.exe --headless --path project --editor --quit || true
          .\godot.exe --headless --path project

  macos-test-project:
    name: Run Test Project (MacOS 🍎)
    runs-on: macos-latest
    steps:
      - name: Checkout Test Repo
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler-test"
          submodules: "false"

      - name: Checkout Godot Object Compiler
        uses: actions/checkout@v6
        with:
          repository: "LucaTuerk/godot-object-compiler"
          submodules: "recursive"
          path: "godot-object-compiler"

      - name: Checkout godot-cpp
        uses: actions/checkout@v6
        with:
          repository: "godotengine/godot-cpp"
          submodules: "true"
          path: "godot-cpp"
          ref: "4.5"

      - name: Install Packages
        run: |
          brew install tree-sitter-cli
          brew install scons

      - name: Setup libclang
        uses: ./godot-object-compiler/.github/actions/setup_libclang
        with:
          platform: "macos"

      - name: Install Godot
        uses: ./godot-object-compiler/.github/actions/setup_godot
        with:
          platform: "macos.universal"
          version: "4.6.3-stable"

      - name: Build Project
        run: |
          mkdir -p build
          cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release -DClang_DIR=${{github.workspace}}/libclang/lib/cmake/clang/
          cmake --build build --parallel $(getconf _NPROCESSORS_ONLN)

      - name: Run Project
        run: |
          ./Godot.app/Contents/MacOS/Godot --headless --path project --editor --quit || true
          ./Godot.app/Contents/MacOS/Godot --headless --path project
