name: Workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check-format:
    uses: ./.github/workflows/format.yml

  linux-build:
    uses: ./.github/workflows/build_linux.yml
    needs: check-format
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

  linux-run-testproject:
    uses: ./.github/workflows/testproject_linux.yml
    needs: check-format

  windows-build:
    uses: ./.github/workflows/build_windows.yml
    needs: check-format

  mac-build:
    uses: ./.github/workflows/build_mac.yml
    needs: check-format
